name: Deploy to server

on: push

jobs:
  first_job:
    name: First Github Action Job
    runs-on: ubuntu-latest
    env:
      NAME: Miguel
    steps:
      - name: Working dir
        run: ls -al
      - name: Action
        uses: actions/checkout@v4
      - name: Working dir after action
        run: ls -al

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: 
      - first_job
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        if: false
        run: echo "Hola Mundo Segundo Job"