name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      NAME: Miguel
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: 
      - first_job
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        if: false
        run: echo "Hola Mundo Segundo Job"