name: Deploy to server

on: push

jobs:
  first_job:
    name: First Github Action Job
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}
    env:
      NAME: Miguel
    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT
      - name: Obtener Mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"  
      - name: Action
        uses: actions/checkout@v4
      - name: Working dir after action
        run: ls -al

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: 
      - first_job
    runs-on: ubuntu-latest
    env:
      SALIDA: ${{ needs.first_job.outputs.salida }}
    steps:
      - name: Hola Mundo
        if: true
        run: echo "$SALIDA"

  third_job:
    name: Subir Artefacto
    runs-on: ubuntu-latest
    steps:
      - name: Generar Archivo
        run: |
          echo "Archivo prueba, hora mundo from Github Actions" >> test.log
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with: 
          name: archivo-test
          path: test.log
  fourth_job:
    name: Descargar artefacto
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with: 
          name: archivo-test
      - name: Cat File
        run: cat test.log

        