name: Deploy to server

on: push

jobs:
  first_job:
    name: First Github Action Job
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}
    env:
      NAME: Miguel
    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT
      - name: Obtener Mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"  
      - name: Action
        uses: actions/checkout@v4
      - name: Working dir after action
        run: ls -al

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: 
      - first_job
    runs-on: ubuntu-latest
    env:
      SALIDA: ${{ needs.first_job.outputs.salida }}
    steps:
      - name: Hola Mundo
        if: true
        run: echo "$SALIDA"